services:
  db-app:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: app_db_user
      POSTGRES_PASSWORD: app_db_user_password
      POSTGRES_DB: order-auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_db_user -d order-auth" ]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: order-auth-app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-app:5432/order-auth
      SPRING_DATASOURCE_USERNAME: app_db_user
      SPRING_DATASOURCE_PASSWORD: app_db_user_password
    ports:
      - "8081:8081"
    depends_on:
      db-app:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
